version : '3.8'
services : 
  dev-db :  
    image : postgres:13
    ports: 
      - 5423:5432
    environment: 
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : 7130
      POSTGRES_DB : simple
    networks : 
      - prem
networks:
  prem: